"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./ai-controller.test");
require("./certified-cycle-controller.test");
require("./certified-ai-compute-benchmark.test");
require("./certified-apple-event-log.test");
require("./certified-library-diagnostics.test");
require("./certified-patch-mutation-evaluation.test");
require("./certified-transition-diagnostics.test");
require("./cycle-library.test");
require("./cycle-scoring.test");
require("./cycle-repairer.test");
require("./game-engine.test");
require("./graph-validator.test");
require("./head-apple-rectangle-diagnostics.test");
require("./hamiltonian-certificate.test");
require("./high-scores.test");
require("./late-game-free-space-path-solver.test");
require("./multi-terminal-patch-diagnostics.test");
require("./patch-mutation-candidate-cache.test");
require("./patch-mutation-scenarios.test");
require("./patch-mutation-v1-limit-diagnostics.test");
require("./rectangle-path-cache.test");
require("./two-terminal-patch-mutation.test");
require("./two-opt-diagnostics.test");
require("./v2-patch-mutation-scenarios.test");
const testkit_1 = require("./testkit");
void (0, testkit_1.runCollectedTests)();
